import { useState } from "react";
import { useLocation } from "wouter";
import { useStore } from "@/lib/store";
import { useQuery } from "@tanstack/react-query";
import { queryClient } from "@/lib/queryClient";
import { fetchReports, fetchSites } from "@/lib/api";
import { useToast } from "@/hooks/use-toast";
import { Layout } from "@/components/layout";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { FileText, Lock, Unlock, Eye, ArrowLeft, Search, Loader2 } from "lucide-react";

export default function AdminReports() {
  const { user } = useStore();
  const [, setLocation] = useLocation();
  const { toast } = useToast();
  const [searchTerm, setSearchTerm] = useState("");
  const [statusFilter, setStatusFilter] = useState("all");

  const { data: reports = [], isLoading: reportsLoading } = useQuery({
    queryKey: ["/api/reports"],
    queryFn: fetchReports,
    refetchInterval: 10000,
  });

  const { data: sites = [] } = useQuery({
    queryKey: ["/api/sites"],
    queryFn: fetchSites,
  });

  const siteMap = new Map<string, string>();
  sites.forEach((s: any) => {
    siteMap.set(String(s.id), s.contactName || s.name || "Unknown");
  });

  const getSiteName = (siteId: string) => {
    return siteMap.get(String(siteId)) || `Site #${siteId}`;
  };

  const getStatusBadge = (status: string) => {
    switch (status) {
      case "Approved":
        return <Badge data-testid="badge-status-approved" className="bg-emerald-600 hover:bg-emerald-700">Approved</Badge>;
      case "Conditionally Approved":
        return <Badge data-testid="badge-status-conditional" className="bg-amber-500 hover:bg-amber-600">Conditionally Approved</Badge>;
      case "Not Approved":
        return <Badge data-testid="badge-status-not-approved" className="bg-red-600 hover:bg-red-700">Not Approved</Badge>;
      case "Adequate":
        return <Badge data-testid="badge-status-adequate" className="bg-emerald-600 hover:bg-emerald-700">Adequate</Badge>;
      case "Partially Adequate":
        return <Badge data-testid="badge-status-partial" className="bg-amber-500 hover:bg-amber-600">Partially Adequate</Badge>;
      case "Critical Gap":
        return <Badge data-testid="badge-status-critical" className="bg-red-600 hover:bg-red-700">Critical Gap</Badge>;
      default:
        return <Badge data-testid="badge-status-other" variant="outline">{status || "N/A"}</Badge>;
    }
  };

  const availableStatuses = Array.from(
    new Set(
      reports
        .map((r: any) => r.finalStatus)
        .filter((s: any) => typeof s === "string" && s.trim().length > 0)
    )
  ).sort();

  const filteredReports = reports.filter((r: any) => {
    const siteName = getSiteName(r.siteId).toLowerCase();
    const matchesSearch = siteName.includes(searchTerm.toLowerCase());
    const matchesStatus = statusFilter === "all" || r.finalStatus === statusFilter;
    return matchesSearch && matchesStatus;
  });

  if (reportsLoading) {
    return (
      <Layout>
        <div className="flex items-center justify-center min-h-[60vh]">
          <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
        </div>
      </Layout>
    );
  }

  return (
    <Layout>
      <div className="container mx-auto p-6 space-y-6 animate-in fade-in duration-500">
        <div
          className="rounded-xl p-8 text-white mb-2"
          style={{ background: "linear-gradient(135deg, #0066a1 0%, #00857c 100%)" }}
          data-testid="reports-header"
        >
          <div className="flex items-center gap-3 mb-2">
            <FileText className="h-8 w-8" />
            <h1 className="text-3xl font-bold">Generated Reports</h1>
          </div>
          <p className="text-white/80 text-sm">View and manage all site evaluation reports generated by the Innova Trials platform.</p>
        </div>

        <Button
          variant="ghost"
          onClick={() => setLocation("/admin")}
          className="pl-0 hover:pl-2 transition-all"
          data-testid="button-back-dashboard"
        >
          <ArrowLeft className="mr-2 h-4 w-4" /> Back to Dashboard
        </Button>

        <div className="flex flex-col md:flex-row gap-3">
          <div className="relative flex-1 md:max-w-sm">
            <Search className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
            <Input
              placeholder="Search by site name..."
              className="pl-9 bg-white"
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              data-testid="input-search-reports"
            />
          </div>
          <Select value={statusFilter} onValueChange={setStatusFilter}>
            <SelectTrigger className="w-[200px] bg-white" data-testid="select-status-filter">
              <SelectValue placeholder="Filter by status" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All Statuses</SelectItem>
              {availableStatuses.map((status) => (
                <SelectItem key={status} value={status}>{status}</SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>

        <Card>
          <CardContent className="p-0">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Report Version</TableHead>
                  <TableHead>Site Name</TableHead>
                  <TableHead>Final Status</TableHead>
                  <TableHead>Generated At</TableHead>
                  <TableHead>Locked</TableHead>
                  <TableHead>Hash</TableHead>
                  <TableHead className="text-right">Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {filteredReports.map((report: any) => (
                  <TableRow key={report.id} data-testid={`row-report-${report.id}`}>
                    <TableCell>
                      <span className="font-medium" data-testid={`text-version-${report.id}`}>
                        {report.reportVersion || "v1"}
                      </span>
                    </TableCell>
                    <TableCell data-testid={`text-site-${report.id}`}>
                      {getSiteName(report.siteId)}
                    </TableCell>
                    <TableCell>
                      {getStatusBadge(report.finalStatus)}
                    </TableCell>
                    <TableCell data-testid={`text-date-${report.id}`}>
                      {report.generatedAtUtc
                        ? new Date(report.generatedAtUtc).toLocaleDateString("en-US", {
                            year: "numeric",
                            month: "short",
                            day: "numeric",
                            hour: "2-digit",
                            minute: "2-digit",
                          })
                        : "N/A"}
                    </TableCell>
                    <TableCell>
                      {report.isLocked ? (
                        <span className="flex items-center gap-1 text-emerald-600" data-testid={`status-locked-${report.id}`}>
                          <Lock className="h-4 w-4" /> Locked
                        </span>
                      ) : (
                        <span className="flex items-center gap-1 text-muted-foreground" data-testid={`status-unlocked-${report.id}`}>
                          <Unlock className="h-4 w-4" /> Unlocked
                        </span>
                      )}
                    </TableCell>
                    <TableCell>
                      <code className="text-xs bg-gray-100 px-2 py-1 rounded font-mono" data-testid={`text-hash-${report.id}`}>
                        {report.hashSha256 ? report.hashSha256.substring(0, 12) + "..." : "N/A"}
                      </code>
                    </TableCell>
                    <TableCell className="text-right">
                      <Button
                        size="sm"
                        variant="outline"
                        onClick={() => setLocation(`/admin/reports/${report.id}`)}
                        data-testid={`button-view-${report.id}`}
                      >
                        <Eye className="h-4 w-4 mr-1" /> View
                      </Button>
                    </TableCell>
                  </TableRow>
                ))}
                {filteredReports.length === 0 && (
                  <TableRow>
                    <TableCell colSpan={7} className="text-center py-12 text-muted-foreground">
                      <FileText className="h-8 w-8 mx-auto mb-2 opacity-40" />
                      No reports found matching your criteria.
                    </TableCell>
                  </TableRow>
                )}
              </TableBody>
            </Table>
          </CardContent>
        </Card>
      </div>
    </Layout>
  );
}
